service mysql start
service nginx start
service php7.0-fpm start
service postfix start
service dovecot start
service spamassassin start
service opendkim start
service cron start
service syslog-ng start
